### ISSUE TITLE
Some questions about the doom theme.

### ISSUE THREAD

**Issue by Chameleon-fzb** [nvimdev/dashboard-nvim#343]
When the Doom theme loads, the content area flashes. The displayed content moves down.
Here is my configuration.

![code](https://user-images.githubusercontent.com/77980791/232206853-800bf833-7b87-4e49-aa3f-3357e4a2ebfa.png)

https://user-images.githubusercontent.com/77980791/232206653-e5e5dbe4-4d7e-4a58-b4c4-8d476fe29c5f.mp4

I use minimal config and still have this problem.

![code2](https://user-images.githubusercontent.com/77980791/232206736-bef91b44-06ff-4e66-aa93-db59326bc19e.png)

https://user-images.githubusercontent.com/77980791/232206685-0364ff14-a2c4-4511-a846-092e31254d2c.mp4

Using the default theme does not have this problem

![code3](https://user-images.githubusercontent.com/77980791/232207025-3ee6e997-b076-4345-9a7c-db9a2aacce96.png)

https://user-images.githubusercontent.com/77980791/232207193-89116968-1841-43d9-9db5-122eddd76ba1.mp4

**Comment by glepnir** [comment]
you need create a min config and test in clean env. `nvim --clean -u min config` . I don't think this is caused by dashboard.

**Comment by Chameleon-fzb** [comment]
I found this issue and it's not caused by the dashboard plugin.
The cause of the problem is the configuration of bufferline.
This should be an issue caused by the order in which the plugins are loaded.
`
 return {
    'akinsho/bufferline.nvim',
    event = "VeryLazy",
    ...
}
`
Remove this configuration option or change it to another unaffected event.
`
return{.
 'akinsho/bufferline.nvim',
    ...
}
`
Thank you for your answer.
