### ISSUE TITLE
A way to add custom lists to hyper

### ISSUE THREAD

**Issue by twiddli** [nvimdev/dashboard-nvim#345]
**Is your feature request related to a problem? Please describe.**
Hi, great plugin!
I wonder if it's possible to make the center lists extendable in the hyper theme?

**Describe the solution you'd like**
Maybe something like
```lua
center = {
   extend = {
     list_a_function,
     list_b_function
}
}
```

**Describe alternatives you've considered**
None that I can think of. MRU and project lists seem to be hardcoded.

**Additional context**
None

**Comment by glepnir** [comment]
in next version you can write your own theme . it's developing please wait that.
