### ISSUE TITLE
In dashboard, Files opened through the Telecsope, are opened in insert mode

### ISSUE THREAD

**Issue by sadtab** [nvimdev/dashboard-nvim#346]
**Describe the bug**
In the dashboard, any file that is opened with Telescope is opened in insert mode, more precisely in `append` form. It's just like the key `a` is presed after the file is opened with a command like `lua require('telescope.builtin').find_files` in the dashboard, I'm not quite sure if this is a dashboard issue or telescope's one

**To Reproduce**
1. Go to 'dashboard'
2. Run on `lua require('telescope.builtin').find_files`
3. See the file is opened in insert mode

**Expected behavior**
The file should be opened in normal mode

Feel free to close this issue if you do not encounter this issue

**Comment by glepnir** [comment]
debug your nvim config.
