### ISSUE TITLE
The dashboard-nvim not work

### ISSUE THREAD

**Issue by EdwardWong1994** [nvimdev/dashboard-nvim#350]
HI, previously i use vimscript to configure my `vim`, now i change to neovim and start to use `lua`.  I am pretty new to `lua`
. I configure dashboard for neovim but it did not work and still give the default neovim interface. 

My configration process like this:
1. in my `~/.config/nvim/init.lua` file:
`require ("plugin-config/dashboard")`

2. in my `~/.config/nvim/plugin-config/dashboard.lua` file, i configure it like this:

```
local db = require('dashboard')

db.custom_header = {
      '   ⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣴⣶⣶⣶⣶⣶⠶⣶⣤⣤⣀⠀⠀⠀⠀⠀⠀ ',
      ' ⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⣿⣿⣿⠁⠀⢀⠈⢿⢀⣀⠀⠹⣿⣿⣿⣦⣄⠀⠀⠀ ',
      ' ⠀⠀⠀⠀⠀⠀⣴⣿⣿⣿⣿⣿⠿⠀⠀⣟⡇⢘⣾⣽⠀⠀⡏⠉⠙⢛⣿⣷⡖⠀ ',
      ' ⠀⠀⠀⠀⠀⣾⣿⣿⡿⠿⠷⠶⠤⠙⠒⠀⠒⢻⣿⣿⡷⠋⠀⠴⠞⠋⠁⢙⣿⣄ ',
      ' ⠀⠀⠀⠀⢸⣿⣿⣯⣤⣤⣤⣤⣤⡄⠀⠀⠀⠀⠉⢹⡄⠀⠀⠀⠛⠛⠋⠉⠹⡇ ',
      ' ⠀⠀⠀⠀⢸⣿⣿⠀⠀⠀⣀⣠⣤⣤⣤⣤⣤⣤⣤⣼⣇⣀⣀⣀⣛⣛⣒⣲⢾⡷ ',
      ' ⢀⠤⠒⠒⢼⣿⣿⠶⠞⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⣼⠃ ',
      ' ⢮⠀⠀⠀⠀⣿⣿⣆⠀⠀⠻⣿⡿⠛⠉⠉⠁⠀⠉⠉⠛⠿⣿⣿⠟⠁⠀⣼⠃⠀ ',
      ' ⠈⠓⠶⣶⣾⣿⣿⣿⣧⡀⠀⠈⠒⢤⣀⣀⡀⠀⠀⣀⣀⡠⠚⠁⠀⢀⡼⠃⠀⠀ ',
      ' ⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣷⣤⣤⣤⣤⣭⣭⣭⣭⣭⣥⣤⣤⣤⣴⣟⠁    ',
}

db.custom_center = {
    {icon = "  ", desc = 'Recently lastest session    ', shortcut = "Leader s l", action = "RestoreSession"},
    {icon = "  ", desc = "Recently opened files       ", shortcut = "Leader f h", action = "Telescope oldfiles"},
    {icon = "  ", desc = "Find File                   ", shortcut = "leader f f", action = "Telescope find_files"},
    {icon = "  ", desc = "File Browser                ", shortcut = "leader f b", action = "Telescope file_browser"},
    {icon = "  ", desc = "Find Word                   ", shortcut = "leader g g", action = "Telescope live_grep"},
    {icon = "  ", desc = "Open Personal dotfiles      ", shortcut = "leader e e", action = "edit $MYVIMRC"}
}

db.custom_footer = function()
    local footer = {'', '🎉 Have fun with neovim'}
    if packer_plugins ~= nil then
        local count = #vim.tbl_keys(packer_plugins)
        footer[2] = '🎉 neovim loaded ' .. count .. ' plugins'
        for key, value in pairs(packer_plugins) do
            table.insert(footer, '✨  ' .. key)
        end
    end

    return footer
end
```  

3. in my `~/.config/nvim/lua/plugins.lua` file, 

```
  use {
      'glepnir/dashboard-nvim',
      event = 'VimEnter',
     requires = {'Nvim-tree'/nvim-web-devicons'}
}
```

I do think `dashboard` is a fancy plugin but i just can not make it work. Configure my neovim like this, it still use the default interface when open neovim. Anyone can help me about this??

**Comment by glepnir** [comment]
okay looks like you don't update this plugin for a long time. new version dashbaord has been rewrite for a while . the config is not same as before. please read doc for new config.

**Comment by EdwardWong1994** [comment]
> okay looks like you don't update this plugin for a long time. new version dashbaord has been rewrite for a while . the config is not same as before. please read doc for new config.

I have changed the configuration use `hyper` theme  shown in below figure:
![28ed4cc902083a9ea00a17bcb6a3535](https://user-images.githubusercontent.com/96438179/235079819-2c6dacd9-2120-4cd7-bcd5-ddb74ef4bd80.jpg)

But i still have errors shown below. Can you help me to figure out this problem?  I am really new with lua grammar
![781559d53bb1096a7741b92cfb508f3](https://user-images.githubusercontent.com/96438179/235080093-c58d6ee5-37f3-47fe-a0ea-1a7dd46cc802.jpg)

**Comment by glepnir** [comment]
so what's error ? you don't show me

**Comment by EdwardWong1994** [comment]
Can you see the error in below figure?  Because i configure the dashboard for nvim in ipad and i just upload photos in my PC side.
![781559d53bb1096a7741b92cfb508f3](https://user-images.githubusercontent.com/96438179/235080638-7dab4dcf-c93e-451f-8afa-73ed5a7bb0e0.jpg)

**Comment by glepnir** [comment]
looks  like the require failed.  try to remove the event if you are using packer.

**Comment by EdwardWong1994** [comment]
I did use packer, but which event do you specified??  it seems the require in this `require(`dashboard`).setup({})` have problems?
