### ISSUE TITLE
Flickering On Start

### ISSUE THREAD

**Issue by AndreM222** [nvimdev/dashboard-nvim#352]
Sorry for the new bug report after another 😭.  Thank you for your patience and good job with all your plugins.

Tends to be a fast flicker like vim wants to load the default startup and changes to dashboard. 

my configs are the following:
## Startup plugin
https://github.com/AndreM222/Windows-Dotfiles/blob/be551779a09be90f21c98b411823d91eb73df7d7/nvim/lua/andrem222/plugins.lua#L19

## Custom configs
https://github.com/AndreM222/Windows-Dotfiles/blob/main/nvim/after/plugin/startup.lua

**Comment by glepnir** [comment]
IDK what the bug is. andy when you got bug please try a min config to reproduce.

**Comment by AndreM222** [comment]
But I did send the config. one link I marked the part of the code that shows how is being installed and the other link is the custom configuration.

## Link 1
```

local status, packer = pcall(require, 'packer')
if (not status) then
    print("Packer Is Not Installed")
    return
end

vim.cmd [[packadd packer.nvim]]

packer.startup(function(use)
    use {
        'glepnir/dashboard-nvim',
        event = 'VimEnter',
        requires = { 'nvim-tree/nvim-web-devicons' }
    }
end)

```
## Link 2
```
local status, startup = pcall( require ,'dashboard' )
if (not status) then return end

startup.setup({
    config = {
        header ={
            ' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗',
            ' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║',
            ' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║',
            ' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
            ' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
            ' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
            '                                                       ',
        },
        shortcut = {
            {
                desc = ' Files',
                group = 'Label',
                action = 'BrowseFiles',
                key = 'f',
            },
            {
                desc = ' Keymaps',
                group = 'DiagnosticHint',
                action = 'Telescope keymaps',
                key = 'k',
            },
            {
                desc = ' Dotfiles',
                group = 'Number',
                action = 'Telescope file_browser cwd=$HOME/Appdata/local/nvim', -- Change to your dotfiles path
                key = 'd',
            },
            {
                desc = '󰝒 New File',
                group = 'DiagnosticWarn',
                action = 'ene ',
                key = 'e',
            }
        },
        packages = { enable = false },
        footer = {
            "",
            "NVIM v" .. vim.version().major .. "." .. vim.version().minor .. "." .. vim.version().patch
        }
    }
})
```

**Comment by glepnir** [comment]
> Tends to be a fast flicker like vim wants to load the default startup and changes to dashboard.

IDK what you mean. so try to use a min config that only have dashboard plugin to reproduce your problem then show me a gif or video.

**Comment by AndreM222** [comment]
hmmm I reinstalled of my plugins to see if it had something to do with that and now seems to work fine. sorry for the trouble. thanks for the help

**Comment by AndreM222** [comment]
it seems the bug came from lualine

**Comment by glepnir** [comment]
hmm I don't use that plugin .not sure what does it do and for stl I don't think anyone need a heavy plugin

**Comment by nottyl** [comment]
I'm having the same issue, @AndreM222 did you find a solution to it? :(

**Comment by AndreM222** [comment]
> I'm having the same issue, @AndreM222 did you find a solution to it? :(

No solution has been found

**Comment by glepnir** [comment]
not sure what does this happen on new version of dashboard. but when it's complete you can test new version pr.
