### ISSUE TITLE
No longer centered in tmux split panes

### ISSUE THREAD

**Issue by Rexzyy** [nvimdev/dashboard-nvim#355]
Prior to updating, when using tmux and vertical splitting.. The dashboard would re-center itself in the window. It no longer centers, and the text is off the screen. I cannot see which hotkeys are assigned to the recent files to quick pick.

Reproduce:
Use vertical tmux split pane.

Implemented code:
```require('dashboard').setup({
    theme = 'hyper',
    config = {
        week_header = {
            enable = true,
        },
        project = {
            enable = true,
        },
        packages = {
            enable = false,
        };
        footer = {},
        disable_move = true,
        },
    })
```
Expected to re-center itself.

# Dashboard centered on full screen terminal:
![image](https://github.com/nvimdev/dashboard-nvim/assets/19592432/bc5c6b13-931c-4735-9405-168b8ad615c8)

# Dashboard no longer centered with vertical tmux split:
![image](https://github.com/nvimdev/dashboard-nvim/assets/19592432/9a7794b1-3a19-43ae-aa7e-b0ebc4bd8cc2)

**Comment by glepnir** [comment]
why you think it's not centered ? it's centered. header shorcuts etc. about center you have a file too long.  that indent file

**Comment by Rexzyy** [comment]
It used to cut the filename off for me and still show the hotkeys. Double checking

**Comment by glepnir** [comment]
never cut filename before. but it should cut name or set hotkey in head instead of tail when it's too long.

**Comment by Rexzyy** [comment]
You're totally right. Cleared out the history and the hotkeys show now with the filename not being too long. Sorry for the bother but thanks for the quick reply!

**Comment by glepnir** [comment]
should handle this situation .so I reopened this . maybe improve later or next version when i have time ;)
