### ISSUE TITLE
Fail  while launching dashboard with dein.vim

### ISSUE THREAD

**Issue by DedSecer** [nvimdev/dashboard-nvim#365]
**Describe the bug**
Fail  while launching dashboard with dein.vim(using neovim)

**To Reproduce**
execute command 'nvim'

**Expected behavior**
Error output:
`Error detected while processing /home/ds/.config/nvim/dein/.cache/init.vim/.dein/plugin/dashboard.lua:
E5113: Error while calling lua chunk: ...fig/nvim/dein/.cache/init.vim/.dein/plugin/dashboard.lua:9: attempt to
call field 'nvim_create_augroup' (a nil value)
stack traceback:
        ...fig/nvim/dein/.cache/init.vim/.dein/plugin/dashboard.lua:9: in main chunk
Press ENTER or type command to continue`

**Comment by glepnir** [comment]
your neovim version ?

**Comment by DedSecer** [comment]
v0.6.1

**Comment by glepnir** [comment]
too old. update to latest stable.

**Comment by DedSecer** [comment]
I've update to nvim v0.9.0 and there still error out put:
```
Error executing luv callback:
[string ":lua"]:3: E5560: vimL function must not be called in a lua loop callback 
stack traceback:
        [C]: in function 'dein#autoload#_on_lua'
        [string ":lua"]:3: in function <[string ":lua"]:2>
        [C]: in function 'require'
        vim/_init_packages.lua: in function '__index'
        vim/_editor.lua: in function 'callback'
        .../nvim/dein/.cache/init.vim/.dein/lua/dashboard/utils.lua:90: in function <.../nvim/dein/.cache/init.vim/.dein/lua/dashboard/utils.lua:88>
```

**Comment by glepnir** [comment]
dein is vimscript. so I would suggest you try lazy.nvim or packer.
