### ISSUE TITLE
Fix alphabet characters for shortcut (especially MRU files)

### ISSUE THREAD

**Issue by ryoppippi** [nvimdev/dashboard-nvim#374]
Hi!
Is there any way to fix the variety of alphabet characters and order of them for MRU files?

I think they are chosen randomly right now, but I want to fix them.

**Comment by glepnir** [comment]
just `table.sort(vim.v.oldfiles)`  maybe also need remove home first .

**Comment by ryoppippi** [comment]
![スクリーンショット 2023-08-07 9 30 09](https://github.com/nvimdev/dashboard-nvim/assets/1560508/b8b56a50-2953-4583-abad-d1c801b4376c)
I mean these alphabets

**Comment by glepnir** [comment]
oh you mean shortcut . I can do sort on new version .

**Comment by ryoppippi** [comment]
Yeah!! Thank you! 
I would like the alphabet to be assigned to shortcut in that order, using an arbitrary alphabetical sequence
