### ISSUE TITLE
Dashboard does not appear on startup on latest neovim commits

### ISSUE THREAD

**Issue by embe221ed** [nvimdev/dashboard-nvim#380]
**Describe the bug**
Dashboard doesn't appear in NeoVim after building it from source on one of the latest commits.
I am not sure which commit breaks the plugin as I didn't have time to check this. However, I built the neovim using this commit: [5d8ab32f3871b0232972cac1116ac7cba98389e5](https://github.com/neovim/neovim/commit/5d8ab32f3871b0232972cac1116ac7cba98389e5) and it works now.
After building neovim from source for few commits which are newer than the `5d8ab32`, the positioning of Dashboard is a little bit different (the dashboard appears higher, not in the center).

**To Reproduce**
1. Build NeoVim from source, latest commit.
2. Run `nvim`
3. Dashboard doesn't appear

**Expected behavior**
Dashboard is opened.

**Screenshots**
can attach, but I think it is obvious what will be on these screenshots.

**Comment by glepnir** [comment]
neovim issue close

**Comment by glepnir** [comment]
@embe221ed  fixed . please update

**Comment by embe221ed** [comment]
do you want me to update the Issue or NeoVim? 😂

**Comment by glepnir** [comment]
no need. you just update the dashboard it works fine now.
