### ISSUE TITLE
Installation with vimplug

### ISSUE THREAD

**Issue by andreaponza** [nvimdev/dashboard-nvim#381]
How can I install dashboard-nvim with viplug?
I put _Plug 'glepnir/dashboard-nvim'_ in _init.vim_ and _:PlugInstall_ is ok, restarting nvim dashboard doesn't work
Where I need to put config file?

**Comment by glepnir** [comment]
did you used neovim ? now it only support neovim

**Comment by andreaponza** [comment]
Yes, neovim 0.9.1 on Mac OSX Ventura

**Comment by Pizza989** [comment]
have the same issue NVIM v0.9.4 on tumbleweed

**Comment by Pizza989** [comment]
for me the solution was to call the setup method like so in the init.vim:
`lua << EOF
require'dashboard'.setup{}
EOF`
i know its pretty stupid alright
