### ISSUE TITLE
Latest dashboard will throw exception while loading

### ISSUE THREAD

**Issue by YangEfei** [nvimdev/dashboard-nvim#383]
**Describe the bug**
I updated my dashboard to the latest version today, but I got the error like later:
```lua
Error executing vim.schedule lua callback: ...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:341: Expected lua string
stack traceback:
        [C]: in function 'nvim_buf_add_highlight'
        ...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:341: in function 'gen_center'
        ...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:439: in function 'callback'
        ...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:155: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
Then I guess it maybe because some configs have break changes. So I remove all of them, and use the default config with Lazy:
```lua
return {
  "glepnir/dashboard-nvim",
  event = "VimEnter",
  config = function()
    require('dashboard').setup {
    }
  end,
  dependencies = { { "nvim-tree/nvim-web-devicons" } },
}
```
It still keeps throwing errors.

**To Reproduce**
Just use the latest version (bbe0234168501b8ba46f24b4fb3cb7c5b88c0784) and default config with Lazy.

**Expected behavior**
Load correctly.

**Screenshots**
![image](https://github.com/nvimdev/dashboard-nvim/assets/54932475/577994ec-6467-4b00-b94a-4719c26f72fa)
![image](https://github.com/nvimdev/dashboard-nvim/assets/54932475/27afb968-8019-46e4-bb61-369ee87efe6c)

**Comment by YangEfei** [comment]
BTW, my nvim version is NVIM v0.10.0-dev.

**Comment by glepnir** [comment]
hmmm I can't reproduce . it works for me everyday.

**Comment by YangEfei** [comment]
I reinstall the dependency nvim-web-devicons, it works correctly.
Thank you for your answer!
