### ISSUE TITLE
Disable folding

### ISSUE THREAD

**Issue by caasi-dev** [nvimdev/dashboard-nvim#386]
**Is your feature request related to a problem? Please describe.**
I have my fold settings set as following:
```
vim.opt.foldlevel = 0
vim.opt.foldmethod = "indent"
```

When dashboard is open all text is folded. See screenshot below.

**Describe the solution you'd like**
Disable the folding on dashboard screen.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/nvimdev/dashboard-nvim/assets/60949037/10bfa807-17ee-4270-8409-c05606a17b84)

**Comment by glepnir** [comment]
because you set foldlevel to 0 . set to 999 to disable.

**Comment by caasi-dev** [comment]
> because you set foldlevel to 0 . set to 999 to disable.

Well, foldlevel is set to 0 intentionally, so when I open any code file is folded by default

**Comment by jakub-gawlik** [comment]
> because you set foldlevel to 0 . set to 999 to disable.

This solution does not resolve the issue... I have the same requirement
