### ISSUE TITLE
how to remove vertical indent lines 

### ISSUE THREAD

**Issue by dlnicoz** [nvimdev/dashboard-nvim#388]
how to remove this vertical lines in dashboard hyper theme

![Screenshot_20230927_002156](https://github.com/nvimdev/dashboard-nvim/assets/92986739/068a3639-4a0c-4eba-a913-01463dc1a481)

**Comment by dlnicoz** [comment]
can anyone help me out ?

**Comment by glepnir** [comment]
you indent plugin should have an option to disable it on dashboard buffer
