### ISSUE TITLE
💥 Breaking changes LuaJIT 5.2

### ISSUE THREAD

**Issue by ProgmRuanSilva** [nvimdev/dashboard-nvim#407]
**Describe the bug**
LuaJit 5.2 changed several methods, **loadstring()** doesn't have more support, and this breaks the hyper theme
in several lines.

So, when I open the neovim an error appears in vim.schedule (see the first screenshot)

Now the suggested method is [load](https://www.lua.org/manual/5.3/manual.html#pdf-load) 
See one article about that: [loadstring](https://forum.cfx.re/t/request-loadstring-lua-function/122926/5)

The unpack() method also are changed.
The suggested method is now [table.unpack](https://stackoverflow.com/questions/65655185/unpack-not-available-on-lua-5-4)

**To Reproduce**
1. Open neovim
2. See error

**Expected behavior**
After these changes I believe, which this works correctly 

**Screenshots**
![image](https://github.com/nvimdev/dashboard-nvim/assets/108758883/bb22d840-bd5d-4303-a788-d1d26c76a898)
![image](https://github.com/nvimdev/dashboard-nvim/assets/108758883/01153a47-2e06-4d2a-921c-b128d565cfcb)
![image](https://github.com/nvimdev/dashboard-nvim/assets/108758883/2f8e49a1-296a-45e5-9e0f-7ec9b5ffbd45)

**Comment by pSchwietzer** [comment]
Can confirm this bug. Current solution to get rid of this error is to simply disable projects in the config:

```lua
config = {
    project = {
        enable = false,
         -- rest of project config
    },
    -- rest of config
}
```

**Comment by ProgmRuanSilva** [comment]
thanks for the help :)
