### ISSUE TITLE
Allow Most Recent Files to be disabled

### ISSUE THREAD

**Issue by scottmckendry** [nvimdev/dashboard-nvim#420]
I really like the hyper layout, especially the weekday header - a very nice touch. However, I was disappointed to find out that I could not disable the most recent files (mru) section. 

I wanted to do something relatively minimal like the screenshot below:
![image](https://github.com/nvimdev/dashboard-nvim/assets/39483124/0bffb072-c2c8-43cc-a5a8-5b29cdec6f29)

My suggestion is to add a new config option `mru.enable` similar to what we already have with `project.enable`. I've created [a fork](https://github.com/nvimdev/dashboard-nvim/commit/11254a05fbf4f03f92f8b94904a1e53ea3342c98) where I've cobbled together a solution for this but it feels a bit hacky and not something I'd open a pull request for. 

Perhaps someone with a better understanding of the code base can do a better job than I can!

**Comment by nicmdev** [comment]
+ 1

**Comment by WawaCallMePepe** [comment]
Such a nice feature, why there is no pull request on it?

**Comment by scottmckendry** [comment]
@WawaCallMePepe I took some time to fix some of the problems I was having with my implementation and have submitted a PR for this feature.
