### ISSUE TITLE
[BUG] Piped standard output to neovim shows the dashboard instead of the buffer with stdout content

### ISSUE THREAD

**Issue by zaerald** [nvimdev/dashboard-nvim#443]
**Describe the bug**
Whenever stdout is piped to neovim, it shows the dashboard instead of the buffer that contains the piped stdout.

This was not an issue in `63df284`.

**To Reproduce**
1. Run `echo "hello" | nvim`
2. It shows the dashboard instead of the piped stdout

**Expected behavior**
The piped stdout should be written to the buffer.

**Screenshots**

Before (`63df284`): 

![dashboard-before](https://github.com/nvimdev/dashboard-nvim/assets/21978370/6409c843-dc4d-417e-bf61-a276575f647a)

After (`39f308a`):

![dashbaord-after](https://github.com/nvimdev/dashboard-nvim/assets/21978370/dc3d5a2e-c4cc-4f31-8aea-6382dd5104c1)

**Comment by yovkov** [comment]
As a workaround until this is fixed, if you use Telescope, do <leader><leader> and then open the Untitled buffer :)

**Comment by illia-danko** [comment]
a little bit annoying: temporary reverted to `c71cab740e2a`

**Comment by infinite-ops** [comment]
I had the same issue, I worked around it by doing this
```
-- Create a group and autocommand to prevent dashboard from starting when stdin is passed
vim.api.nvim_create_augroup("dashboard_stdin", { clear = true })
vim.api.nvim_create_autocmd({ "StdinReadPre" }, {
  group = "dashboard_stdin",
  callback = function()
    vim.g.loaded_dashboard = 1
  end,
})
```

might be someone knows a better way?

**Comment by mangkoran** [comment]
@infinite-ops Your idea is great. However, this makes `Dashboard` function not being loaded, as the code will return here:

https://github.com/nvimdev/dashboard-nvim/blob/1c8b82c5b02bb890862538be2061e37ef801a99b/plugin/dashboard.lua#L2-L4

So we couldn't open `Dashboard` anytime after we opened a file from stdin.

I have made a commit inspired from https://github.com/nvimdev/dashboard-nvim/issues/443#issuecomment-2081682699 in my fork: https://github.com/mangkoran/dashboard-nvim/commit/74c80ec32a9ccf068fa5d5916eee1716f83cb2f2

The only caveat is that we need to not lazy-load the plugin (e.g. if you use LazyVim)

Please give it a try!

**Comment by infinite-ops** [comment]
Thanks! Tried your feature and it doesn't work with my config as below, but if I change to as you say `lazy = false` then it does indeed work. Plus Dashboard works too when its the stdin content and then you call it, I hadnt noticed it didnt work as I dont use that feature!
```
  {
    "nvimdev/dashboard-nvim",
      event = "VimEnter",
      config = function()
      require "plugins._dashboard"
    end,
    dependencies = { { "nvim-tree/nvim-web-devicons" } },
  },
```

nice one @mangkoran !

**Comment by mangkoran** [comment]
> Thanks! Tried your feature and it doesn't work with my config as below, but if I change to as you say lazy = false then it does indeed work.

Yeah this is due to `StdinReadPre` event is triggered before `VimEnter`. So if `dashboard-nvim` is lazy-loaded on `VimEnter` event as LazyVim current config, the `StdinReadPre` autocmd will never called.

**Comment by infinite-ops** [comment]
ahh. Thanks for the explanation :)

**Comment by raffaem** [comment]
So the official solution to this is to use `lazy=false` in the config?

**Comment by karl-gustav** [comment]
Don't know if it's official, but `lazy = false,` in the lazy plugin config fixes the problem.
