### ISSUE TITLE
lualine is disappeared

### ISSUE THREAD

**Issue by anhoder** [nvimdev/dashboard-nvim#456]
**Describe the bug**

This commit(6da86d8b1f07d21b48398231fec6ff6da106f9af) caused my lualine to disappear and I had to rollback to 5182c09ac8085dc73b78ad0ea9f5479c9a866fc4

**To Reproduce**
1. upgrade dashboard to 6da86d8b1f07d21b48398231fec6ff6da106f9af
2. enter dashboard
3. open file or project in dashboard
4. lualine is missing...

**Expected behavior**
has lualine
<img width="1676" alt="image" src="https://github.com/nvimdev/dashboard-nvim/assets/27605589/638a61a0-452f-4232-92ac-a4b4c4cea085">
 

**Screenshots**
now
![image](https://github.com/nvimdev/dashboard-nvim/assets/27605589/c63cbbe8-be66-44a2-8f14-36de495fe9f8)

**Comment by folke** [comment]
Same in LazyVim

**Comment by glepnir** [comment]
after revert can close now ?

**Comment by folke** [comment]
yes, all good now! :)

**Comment by glepnir** [comment]
@folke  btw it's time to write lazyline  lol
